"""Short, iconed, clickable display for the LinkedIn/GitHub/portfolio links in
the contact line.

Resumes conventionally show these as a small platform icon plus the bare
handle -- e.g. the LinkedIn badge + "/bhaveshbhargv" -- rather than the word
"LinkedIn" or the full URL: shorter, and it still reads as exactly what it
links to. The two badge icons (assets/icons/linkedin.png, github.png) are
small original rounded-square badges generated by scripts/generate_social_icons.py
(NOT either company's actual logo artwork), committed as static files so
nothing needs to be drawn at request time.

Used by the HTML preview and both document exporters, so the same icon +
handle shows everywhere and always links to the real URL, not just on screen.
"""
from __future__ import annotations

import base64
import os
from urllib.parse import urlparse

from utils.validators import normalize_url

_ASSETS_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "assets", "icons"))
LINKEDIN_ICON_PATH = os.path.join(_ASSETS_DIR, "linkedin.png")
GITHUB_ICON_PATH = os.path.join(_ASSETS_DIR, "github.png")


def display_href(url: str) -> str:
    """A safe, scheme-qualified href for `url` ("" stays "")."""
    return normalize_url(url)


def _host(url: str) -> str:
    return urlparse(normalize_url(url)).netloc.lower()


def _path_segments(url: str) -> list:
    path = urlparse(normalize_url(url)).path.strip("/")
    return path.split("/") if path else []


def is_github_url(url: str) -> bool:
    host = _host(url)
    return host == "github.com" or host.endswith(".github.com")


def linkedin_handle(url: str) -> str:
    segments = _path_segments(url)
    return segments[-1] if segments else ""


def github_handle(url: str) -> str:
    segments = _path_segments(url)
    return segments[0] if segments else ""


def portfolio_domain_label(url: str) -> str:
    """Bare hostname for a non-GitHub portfolio link (no matching icon for
    an arbitrary site), e.g. 'janedoe.dev' from 'https://www.janedoe.dev'."""
    host = _host(url)
    if host.startswith("www."):
        host = host[4:]
    return host or "Portfolio"


def _data_uri(path: str) -> str:
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def linkedin_icon_data_uri() -> str:
    return _data_uri(LINKEDIN_ICON_PATH)


def github_icon_data_uri() -> str:
    return _data_uri(GITHUB_ICON_PATH)
